### PR TITLE
fix: change rounding parameters to use defaults

### PR DESCRIPTION
**Pull request by byhashdong**
This commit updates the uniswap-sdk-core-rust from version 3.1.0 to 3.2.0.
https://github.com/malik672/uniswap-sdk-core-rust/pull/89

## Release Notes

- **New Features**
  - Enhanced `Pool` struct with improved price calculation flexibility and better error handling for token validation.
  - Updated `Trade` struct with new methods for calculating worst execution price and price impact, including slippage checks.
  - Improved `Route` struct with refined mid-price calculations.
  
- **Bug Fixes**
  - Refined error handling in trade execution and price calculations to ensure robustness.

- **Documentation**
  - Minor updates to test cases to reflect changes in method parameters and improve clarity on rounding strategies.

### CODE REVIEW

**Comment by byhashdong** [comment]
@shuhuiluo, could you please review this?

**Review by shuhuiluo — CHANGES_REQUESTED** [review]
Thanks. But `Some(Rounding::RoundHalfUp)` should be replaced by `None`.

**Comment by byhashdong** [comment]
@shuhuiluo, apologies for the confusion! Since all the test functions are running smoothly, I'm a bit perplexed. Could you provide a brief explanation? Thank you!

**Comment by shuhuiluo** [comment]
> @shuhuiluo, apologies for the confusion! Since all the test functions are running smoothly, I'm a bit perplexed. Could you provide a brief explanation? Thank you!

Take a look at https://github.com/malik672/uniswap-sdk-core-rust/pull/89 for the default behavior.

**Comment by byhashdong** [comment]
Indeed, since `to_significant`/`to_fixed` unwraps `NONE` to `Rounding::RoundHalfUp`, it is sufficient to pass `NONE` rather than `Rounding::RoundHalfUp`?

**Comment by shuhuiluo** [comment]
> Indeed, since `to_significant`/`to_fixed` unwraps `NONE` to `Rounding::RoundHalfUp`, it is sufficient to pass `NONE` rather than `Rounding::RoundHalfUp`?

Yes.

**Review by shuhuiluo — CHANGES_REQUESTED** [review]
Please fix format.

**Comment by byhashdong** [comment]
Sure!

**Review by shuhuiluo — APPROVED** [review]
Lgtm.

**Pull request merged**
